### ISSUE TITLE
Cooking achievement - clarification/bug

### ISSUE THREAD

**Issue by anton-shestakov** [smitty-diamond-hunt/idle-pixel-bug-tracking#2]
How to complete following achievement?

_Successfully cook some food without the recommended cooking level._

I've tried that using chicken meat that is dropped from monster. It has no recommended level in tooltip, but when cooked it didn't complete this achievement. 

https://user-images.githubusercontent.com/21039120/180389029-2443f35a-6517-4eb7-8b49-5dc8296e3bb6.mp4

![cooking_achievement_bug_after](https://user-images.githubusercontent.com/21039120/180389038-6ea5409a-ef3b-435f-ad77-98899c98673a.png)

**Comment by smitty-diamond-hunt** [comment]
This achievement might  be confusing, so I'll try to clarify and maybe change tooltip descriptions to make it clearer for players.

Basically, each raw food that can be cooked has a recommended cooking level to cook it.  If the player is under the recommended level, there is an increased burn rate of 40%.  So with a bronze oven, we're talking 90% burn rate.

The raw chicken has a recommended cooking level of 1, which is why it's not displayed on the tooltip.

If you try to cook any food with a recommended level of which your cooking is lower (click cook on a high level fish for example) - you'll get a second message notifying you that you do not have the recommended level but can still try to cook it.  This will trigger the achievement.

**Comment by anton-shestakov** [comment]
Got it. Cooking crab worked as expected :+1: 

Yeah, I think tooltip should say something about _higher_ recommended cooking level.
